language: java

dist: xenial

jdk:
  - openjdk8
  - openjdk11

cache:
  directories:
    - $HOME/.m2

sudo: false

before_script: travis_retry mvn -B help:active-profiles

script: travis_retry mvn -B verify -Pits

addons:
   apt:
      packages:
         - rpm
