language: java

jdk:
  - oraclejdk8
  - oraclejdk10

cache:
  directories:
    - $HOME/.m2

sudo: false

before_script: travis_retry mvn -B help:active-profiles

script: travis_retry mvn -B verify -Pits

addons:
   apt:
      packages:
         - rpm
