language: java

jdk:
  - oraclejdk8
  - oraclejdk10

cache:
  directories:
    - $HOME/.m2

sudo: false

script: travis_retry mvn -B integration-test -Pits

addons:
   apt:
      packages:
         - rpm